### ISSUE TITLE
repo里直接塞zip这合理吗（（

### ISSUE THREAD

**Issue by undefined-moe** [iceBear67/Katsuhisa#2]

**Comment by iceBear67** [comment]
就且当作是方便clone下来的读者把（  
mcbbs上应该挺多人科学上网都是问题

**Comment by iceBear67** [comment]
啊....就当方便发布之后下载离线查看吧（然而图片也不太行


 
---原始邮件---
发件人: "undefined"<notifications@github.com&gt;
发送时间: 2021年2月17日 21:41:39
收件人: "iceBear67/Katsuhisa"<Katsuhisa@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [iceBear67/Katsuhisa] repo里直接塞zip这合理吗（（ (#2)

**Comment by undefined-moe** [comment]
> 就且当作是方便clone下来的读者把（
> mcbbs上应该挺多人科学上网都是问题

小知识： github.com的clone速度在国内多数地区可达13KiB/s，接近百度云的三分之一

**Comment by iceBear67** [comment]
我打算手动clone过去或者码云镜像（
